sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

script:
  - python -m compileall ./ -f
  - pip install -e Rule34-API-Wrapper --upgrade
  - python Rule34-API-Wrapper/rule34.py
