sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov
  - pip install pytest-cov

script:
  - python -m compileall ./ -f
  - pip install -e Rule34-API-Wrapper --upgrade
  - cd Rule34-API-Wrapper/rule34
  - pytest --cov=rule34 -v

after_success:
  - codecov