sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov
  - pip install pytest-cov

script:
  - python -m compileall ./ -f
  - python Rule34-API-Wrapper/setup.py install
  - cd Rule34-API-Wrapper
  - pytest --cov=rule34 -v

after_success:
  - codecov