sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install codecov

script:
  - python -m compileall ./ -f
  - pip install -e Rule34-API-Wrapper --upgrade
  - coverage run Rule34-API-Wrapper/rule34.py

after_success:
  - codecov